### PR TITLE
Update OliCommand.java

### PR DESCRIPTION
**Pull request by spaceghost24**
I added a random comment in Oli_command to demonstrate the pull request

### CODE REVIEW

**Review by FridgeRaider23 — APPROVED** [review]
b

**Review by TomP6 — APPROVED** [review]

**Review by Mindi088 — COMMENTED** [review]
cool

**Comment by FridgeRaider23** [comment]
В кузне травел сидечик, огурный зеленечик

**Review by TomP6 — COMMENTED** [review]
yes in another language

**Comment by FridgeRaider23** [comment]
> yes in another language

try putting in it google translate

**Review by Mindi088 — COMMENTED** [review]
这个写的非常好

**Comment by spaceghost24** [comment]
> 这个写的非常好

Muchas grácias :)

**Pull request merged**
